# Generated by Django 4.2.8 on 2025-07-19 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the applicant",
                        max_length=100,
                        verbose_name="full name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the applicant",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number of the applicant",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Position the applicant is applying for",
                        max_length=100,
                        verbose_name="position applied for",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department of the position",
                        max_length=50,
                        verbose_name="department",
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the application was submitted",
                        verbose_name="application date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("interview", "Interview"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        help_text="Current status of the application",
                        max_length=20,
                        verbose_name="application status",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Entry-level", "Entry Level"),
                            ("Mid-level", "Mid Level"),
                            ("Mid-Senior", "Mid-Senior"),
                            ("Senior", "Senior"),
                        ],
                        help_text="Experience level of the applicant",
                        max_length=20,
                        verbose_name="experience level",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location of the applicant",
                        max_length=100,
                        verbose_name="location",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        help_text="Rating given by the reviewer (0-5)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL",
                        verbose_name="LinkedIn URL",
                    ),
                ),
                (
                    "portfolio",
                    models.URLField(
                        blank=True,
                        help_text="Portfolio or website URL",
                        verbose_name="portfolio URL",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True,
                        help_text="Cover letter text",
                        verbose_name="cover letter",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Resume file (PDF, DOC, DOCX)",
                        null=True,
                        upload_to="resumes/",
                        verbose_name="resume",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was reviewed",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the application",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "db_table": "job_applications",
                "ordering": ["-applied_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "applied_date"],
                        name="job_applica_status_8bf581_idx",
                    ),
                    models.Index(
                        fields=["department", "position"],
                        name="job_applica_departm_19d08a_idx",
                    ),
                    models.Index(fields=["email"], name="job_applica_email_ac334c_idx"),
                ],
            },
        ),
    ]
