# Generated by Django 4.2.8 on 2025-06-06 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookingPayment",
        ),
    ]
