# Generated by Django 4.2.8 on 2025-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_remove_booking_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="vehicle_make_model",
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle_state",
            field=models.CharField(default="NY", max_length=2),
        ),
    ]
