# Generated by Django 4.2.8 on 2025-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_remove_booking_vehicle_make_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="actual_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When user actually checked out", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="actual_start_time",
            field=models.DateTimeField(
                blank=True, help_text="When user actually checked in", null=True
            ),
        ),
    ]
