# Generated by Django 4.2.8 on 2025-06-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_actual_end_time_booking_actual_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="auto_checkout",
            field=models.BooleanField(
                default=False, help_text="Whether checkout was performed automatically"
            ),
        ),
    ]
