# Generated by Django 4.2.8 on 2025-06-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="is_instant_book",
            field=models.BooleanField(
                default=False,
                help_text="Whether verified users can book this space instantly without approval",
                verbose_name="instant book enabled",
            ),
        ),
    ]
