# Generated by Django 4.2.8 on 2025-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_parkinglisting_is_instant_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="has_car_wash",
            field=models.BooleanField(
                default=False,
                help_text="Whether car washing services are available",
                verbose_name="car wash",
            ),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="has_cctv",
            field=models.BooleanField(
                default=False,
                help_text="Whether the area has CCTV video surveillance",
                verbose_name="CCTV monitoring",
            ),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="has_gated_access",
            field=models.BooleanField(
                default=False,
                help_text="Whether the parking area has controlled/gated access",
                verbose_name="gated access",
            ),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="has_lighting",
            field=models.BooleanField(
                default=False,
                help_text="Whether the parking area has good lighting for safety",
                verbose_name="well lit",
            ),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="has_valet_service",
            field=models.BooleanField(
                default=False,
                help_text="Whether valet parking service is available",
                verbose_name="valet service",
            ),
        ),
        migrations.AddField(
            model_name="parkinglisting",
            name="is_handicap_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether the parking space is ADA compliant",
                verbose_name="handicap accessible",
            ),
        ),
    ]
