# Generated by Django 4.2.8 on 2025-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "listings",
            "0003_parkinglisting_has_car_wash_parkinglisting_has_cctv_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglisting",
            name="availability_schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Weekly availability schedule",
                verbose_name="availability schedule",
            ),
        ),
    ]
