# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_parkinglisting_availability_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglisting',
            name='approval_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending Review'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('REVISION_REQUESTED', 'Revision Requested')
                ],
                default='PENDING',
                help_text='Admin approval status for this listing',
                max_length=20,
                verbose_name='approval status'
            ),
        ),
        migrations.AddField(
            model_name='parkinglisting',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Admin who reviewed this listing',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_listings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='reviewed by'
            ),
        ),
        migrations.AddField(
            model_name='parkinglisting',
            name='reviewed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the listing was reviewed',
                null=True,
                verbose_name='reviewed at'
            ),
        ),
        migrations.AddField(
            model_name='parkinglisting',
            name='admin_notes',
            field=models.TextField(
                blank=True,
                help_text='Notes from admin review',
                verbose_name='admin notes'
            ),
        ),
        migrations.AddField(
            model_name='parkinglisting',
            name='rejection_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason for rejection if applicable',
                max_length=200,
                verbose_name='rejection reason'
            ),
        ),
        migrations.AddIndex(
            model_name='parkinglisting',
            index=models.Index(fields=['approval_status'], name='listings_pa_approva_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinglisting',
            index=models.Index(fields=['reviewed_by', 'reviewed_at'], name='listings_pa_reviewe_idx'),
        ),
    ]