# Generated by Django 4.2.x

from django.db import migrations


def approve_existing_listings(apps, schema_editor):
    """
    Approve all existing listings that were created before the approval system.
    This prevents existing listings from disappearing when the approval filter is applied.
    """
    ParkingListing = apps.get_model('listings', 'ParkingListing')
    
    # Update all existing listings to APPROVED status
    # This assumes that listings created before the approval system should be grandfathered in
    updated_count = ParkingListing.objects.filter(
        approval_status='PENDING'
    ).update(approval_status='APPROVED')
    
    print(f"Approved {updated_count} existing listings for backward compatibility")


def reverse_approve_existing_listings(apps, schema_editor):
    """
    Reverse the approval of existing listings.
    """
    ParkingListing = apps.get_model('listings', 'ParkingListing')
    
    # Revert all approved listings back to pending
    # (This is not a perfect reverse since we can't distinguish between
    # listings that were auto-approved vs manually approved, but it's safe)
    reverted_count = ParkingListing.objects.filter(
        approval_status='APPROVED'
    ).update(approval_status='PENDING')
    
    print(f"Reverted {reverted_count} listings back to pending status")


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_admin_approval_fields'),
    ]

    operations = [
        migrations.RunPython(
            approve_existing_listings,
            reverse_approve_existing_listings,
        ),
    ]