# Generated by Django 4.2.8 on 2025-06-22 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0006_add_covered_space_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parkinglisting",
            name="listings_pa_approva_idx",
        ),
        migrations.RemoveIndex(
            model_name="parkinglisting",
            name="listings_pa_reviewe_idx",
        ),
        migrations.AlterField(
            model_name="parkinglisting",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this listing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
