# Generated by Django 4.2.8 on 2025-07-19 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_approve_existing_listings"),
        ("listings", "0007_remove_parkinglisting_listings_pa_approva_idx_and_more"),
    ]

    operations = []
