# Generated by Django 4.2.8 on 2025-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_merge_20250719_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglisting",
            name="space_type",
            field=models.CharField(
                choices=[
                    ("garage", "Garage"),
                    ("lot", "Parking lot"),
                    ("covered", "Covered space"),
                    ("driveway", "Driveway"),
                ],
                help_text="Type of parking space",
                max_length=20,
                verbose_name="space type",
            ),
        ),
    ]
