#!/bin/bash

# Backend Emergency Fix Script
# This script helps fix the 500 errors on the production backend

echo "🚨 Backend Emergency Fix Script"
echo "================================"
echo ""
echo "The backend is currently returning 500 errors for all APIs."
echo "This is likely due to disabled messaging/disputes apps breaking Django."
echo ""
echo "To fix this, SSH into the backend server and run these commands:"
echo ""
echo "ssh root@165.227.111.160"
echo ""
echo "# Navigate to project directory"
echo "cd /var/www/parking-in-a-pinch"
echo ""
echo "# Check current status"
echo "source venv/bin/activate"
echo "python manage.py check"
echo ""
echo "# Check Django settings for disabled apps"
echo "python manage.py shell -c \"from django.conf import settings; print([app for app in settings.INSTALLED_APPS if 'messaging' in app or 'disputes' in app])\""
echo ""
echo "# Option 1: Re-enable the apps if they exist"
echo "# Edit settings.py to uncomment messaging and disputes apps"
echo "nano apps/core/settings.py"
echo ""
echo "# Option 2: Completely remove disabled app references"
echo "# Remove any URL imports or references to messaging/disputes"
echo "nano urls.py"
echo ""
echo "# Run migrations to fix any database issues"
echo "python manage.py migrate"
echo ""
echo "# Collect static files"
echo "python manage.py collectstatic --noinput"
echo ""
echo "# Restart services"
echo "sudo systemctl restart gunicorn"
echo "sudo systemctl restart nginx"
echo ""
echo "# Test the fix"
echo "curl -I http://localhost/api/listings/"
echo ""
echo "🔍 Common issues to check:"
echo "1. Commented out apps in INSTALLED_APPS that are still referenced in URLs"
echo "2. Missing database tables for disabled apps"
echo "3. Import errors from disabled apps"
echo "4. Middleware or authentication dependencies"
echo ""
echo "🎯 Quick diagnostic commands:"
echo "python manage.py check --deploy"
echo "python manage.py showmigrations"
echo "tail -f /var/log/gunicorn/error.log"
echo "tail -f /var/log/nginx/error.log"