services:
  # Backend Django service
  - type: web
    name: parking-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true

  # Frontend React service  
  - type: web
    name: parking-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://parking-backend.onrender.com/api
    autoDeploy: true

databases:
  - name: parking-db
    plan: free
    databaseName: parking_pinch
    user: parking_user