# Generated by Django 4.2.8 on 2025-06-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="message_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("reminder", "Reminder"),
                    ("emergency", "Emergency"),
                    ("marketing", "Marketing"),
                    ("system", "System"),
                    ("message", "Message"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("reminder", "Reminder"),
                    ("emergency", "Emergency"),
                    ("marketing", "Marketing"),
                    ("system", "System"),
                    ("message", "Message"),
                ],
                max_length=20,
            ),
        ),
    ]
