# Generated by Django 4.2.8 on 2025-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="primary_vehicle_state",
            field=models.CharField(
                blank=True,
                help_text="State where primary vehicle is registered",
                max_length=2,
                verbose_name="primary vehicle state",
            ),
        ),
    ]
