# Generated by Django 4.2.8 on 2025-06-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_primary_vehicle_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("IDENTITY", "Identity Verification"),
                            ("PHONE", "Phone Verification"),
                            ("EMAIL", "Email Verification"),
                        ],
                        default="IDENTITY",
                        max_length=20,
                        verbose_name="verification type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "id_document_front",
                    models.ImageField(
                        blank=True,
                        help_text="Front side of government-issued ID",
                        null=True,
                        upload_to="verification/id_documents/",
                        verbose_name="ID document front",
                    ),
                ),
                (
                    "id_document_back",
                    models.ImageField(
                        blank=True,
                        help_text="Back side of government-issued ID",
                        null=True,
                        upload_to="verification/id_documents/",
                        verbose_name="ID document back",
                    ),
                ),
                (
                    "selfie_with_id",
                    models.ImageField(
                        blank=True,
                        help_text="Selfie holding the ID document",
                        null=True,
                        upload_to="verification/selfies/",
                        verbose_name="selfie with ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of ID document (e.g., Driver License, Passport)",
                        max_length=50,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number (encrypted for security)",
                        max_length=100,
                        verbose_name="document number",
                    ),
                ),
                (
                    "document_expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="When the document expires",
                        null=True,
                        verbose_name="document expiry date",
                    ),
                ),
                (
                    "verification_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional verification information",
                        verbose_name="verification data",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was reviewed",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from admin review",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for rejection if applicable",
                        max_length=200,
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Request",
                "verbose_name_plural": "Verification Requests",
                "db_table": "verification_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "verification_type"],
                        name="verificatio_user_id_8b0213_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="verificatio_status_3781c6_idx",
                    ),
                    models.Index(
                        fields=["reviewed_by", "reviewed_at"],
                        name="verificatio_reviewe_55aec3_idx",
                    ),
                ],
            },
        ),
    ]
