# Generated by Django 4.2.8 on 2025-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_verificationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribe_to_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user wants to receive marketing emails",
                verbose_name="subscribe to newsletter",
            ),
        ),
    ]
