# Generated by Django 4.2.8 on 2025-07-19 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_admin_verification_fields"),
        ("users", "0004_add_subscribe_to_newsletter"),
    ]

    operations = []
