name: parking-in-a-pinch
services:
  # Backend Django API
  - name: backend
    source_dir: /backend
    github:
      repo: your-username/parking-in-a-pinch
      branch: main
      deploy_on_push: true
    run_command: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/v1/health/
    routes:
      - path: /api
    envs:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: ALLOWED_HOSTS
        value: "${APP_DOMAIN},*.ondigitalocean.app"
      - key: SECRET_KEY
        type: SECRET
      - key: DATABASE_URL
        type: SECRET
      - key: REDIS_URL
        type: SECRET
      - key: STRIPE_PUBLIC_KEY
        type: SECRET
      - key: STRIPE_SECRET_KEY
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        type: SECRET
      - key: GOOGLE_MAPS_API_KEY
        type: SECRET
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@parkinginapinch.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        type: SECRET
      - key: EMAIL_HOST_PASSWORD
        type: SECRET

  # Frontend React App
  - name: frontend
    source_dir: /frontend
    github:
      repo: your-username/parking-in-a-pinch
      branch: main
      deploy_on_push: true
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_BASE_URL
        value: "${backend.PUBLIC_URL}/api/v1"
      - key: VITE_GOOGLE_MAPS_API_KEY
        type: SECRET
      - key: VITE_STRIPE_PUBLIC_KEY
        type: SECRET

# Managed Database
databases:
  - name: parking-db
    engine: PG
    version: "15"
    production: true
    cluster_name: parking-cluster

# Redis for caching and sessions
services:
  - name: redis
    engine: REDIS
    version: "7"
    production: true