# Generated by Django 4.2.8 on 2025-06-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0004_booking_actual_end_time_booking_actual_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_id",
                    models.CharField(
                        help_text="Unique dispute identifier",
                        max_length=20,
                        unique=True,
                        verbose_name="dispute ID",
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("host_issue", "Issue with Host"),
                            ("renter_issue", "Issue with Renter"),
                            ("refund_request", "Refund Request"),
                            ("property_damage", "Property Damage"),
                            ("no_show", "No Show"),
                            ("billing_issue", "Billing Issue"),
                            ("other", "Other"),
                        ],
                        help_text="Type of dispute",
                        max_length=20,
                        verbose_name="dispute type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief description of the dispute",
                        max_length=200,
                        verbose_name="subject",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the issue",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        help_text="Current status of the dispute",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the dispute",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "disputed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in dispute (if applicable)",
                        max_digits=10,
                        null=True,
                        verbose_name="disputed amount",
                    ),
                ),
                (
                    "refund_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a refund is being requested",
                        verbose_name="refund requested",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of refund requested",
                        max_digits=10,
                        null=True,
                        verbose_name="refund amount",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for admin use",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True,
                        help_text="Final resolution of the dispute",
                        verbose_name="resolution",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the dispute was resolved",
                        null=True,
                        verbose_name="resolved at",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user assigned to this dispute",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related booking (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "complainant",
                    models.ForeignKey(
                        help_text="User filing the dispute",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        help_text="User being disputed against (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message content", verbose_name="message"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an internal admin message",
                        verbose_name="internal message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        help_text="Dispute this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Message",
                "verbose_name_plural": "Dispute Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="dispute_attachments/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the file",
                        max_length=500,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        help_text="Dispute this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Attachment",
                "verbose_name_plural": "Dispute Attachments",
                "ordering": ["created_at"],
            },
        ),
    ]
