# Generated by Django 4.2.8 on 2025-07-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
        ("disputes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated conversation for dispute messages",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="messaging.conversation",
            ),
        ),
    ]
