# Generated by Django 4.2.8 on 2025-07-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0004_update_payout_method_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutrequestpayments",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="payoutrequestpayments",
            name="payoutrequest",
        ),
        migrations.RemoveIndex(
            model_name="payoutrequest",
            name="payout_requ_review_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="payoutrequest",
            new_name="payout_requ_status_3ce346_idx",
            old_name="payout_requ_status_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="payoutrequest",
            new_name="payout_requ_host_id_c0c4a2_idx",
            old_name="payout_requ_host_d4e5f6_idx",
        ),
        migrations.AlterField(
            model_name="payoutrequest",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Bank account number (last 4 digits shown)",
                max_length=50,
                verbose_name="account number",
            ),
        ),
        migrations.AlterField(
            model_name="payoutrequest",
            name="host_notes",
            field=models.TextField(
                blank=True, help_text="Notes from the host", verbose_name="host notes"
            ),
        ),
        migrations.AlterField(
            model_name="payoutrequest",
            name="payments",
            field=models.ManyToManyField(
                help_text="Payments to be included in this payout",
                related_name="payout_requests",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payoutrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_payout_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrequest",
            index=models.Index(
                fields=["request_id"], name="payout_requ_request_192762_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PayoutRequestPayments",
        ),
    ]
